# Generated by Django 4.2.27 on 2026-01-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_expense_purchaseinvoice_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='installment_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('installment', 'Installment')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
