# Generated by Django 4.2.27 on 2026-01-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_salesinvoice_installment_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'غير مدفوعة'), ('partial', 'مدفوعة جزئياً'), ('paid', 'مدفوعة بالكامل')], default='unpaid', max_length=20),
        ),
    ]
