# Generated by Django 4.2.27 on 2026-01-07 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_salesinvoice_paid_amount_salesinvoice_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'غير مدفوعة'), ('partial', 'مدفوعة جزئياً'), ('paid', 'مدفوعة بالكامل')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='returninvoice',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.purchaseinvoice'),
        ),
        migrations.AddField(
            model_name='returninvoice',
            name='sale_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.salesinvoice'),
        ),
    ]
