# Generated by Django 4.2.27 on 2026-01-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_supplierbalance_customerbalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierbalance',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='CustomerBalance',
        ),
        migrations.DeleteModel(
            name='SupplierBalance',
        ),
    ]
