# Generated by Django 5.2.10 on 2026-01-17 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectBasic',
        ),
    ]
