# Generated by Django 5.2.6 on 2025-12-26 17:39

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = [
  ]

  operations = [
      migrations.CreateModel(
          name='Customers',
          fields=[
              ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
              ('name', models.TextField()),
              ('phone', models.CharField(blank=True, max_length=30, null=True)),
              ('address', models.TextField(blank=True, null=True)),
              ('blocked', models.BooleanField(default=False)),
              ('vip', models.BooleanField(default=False)),
              ('notes', models.TextField(blank=True, null=True)),
              ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
              ('updated_at', models.DateTimeField(auto_now=True)),
          ],
      ),
      migrations.CreateModel(
          name='Suppliers',
          fields=[
              ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
              ('person_name', models.CharField(max_length=255)),
              ('company_name', models.CharField(blank=True, max_length=255, null=True)),
              ('phone', models.CharField(blank=True, max_length=30, null=True)),
              ('address', models.TextField(blank=True, null=True)),
              ('active', models.BooleanField(default=True)),
              ('notes', models.TextField(blank=True, null=True)),
              ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
              ('updated_at', models.DateTimeField(auto_now=True)),
          ],
      ),
  ]
