# Generated by Django 4.2.27 on 2025-12-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_add_otp_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='temp_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
