# Generated by Django 4.2.27 on 2026-01-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_otpverification_temp_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
