# Generated by Django 5.2.6 on 2025-12-31 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPs',
        ),
    ]
