# Generated by Django 4.2.27 on 2026-01-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_delete_otps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='verified',
        ),
    ]
