# Generated by Django 4.2.27 on 2026-01-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(default=201101023681, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
