# Generated by Django 6.0.1 on 2026-01-17 17:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_users_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPasswordRequests',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forgot_password_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='authenticat_user_id_2a3d6d_idx'), models.Index(fields=['token_hash'], name='authenticat_token_h_24995e_idx'), models.Index(fields=['expires_at'], name='authenticat_expires_3842c4_idx')],
            },
        ),
    ]
