# Generated by Django 6.0.1 on 2026-01-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_forgotpasswordrequests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgotpasswordrequests',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='forgotpasswordrequests',
            name='user_agent',
        ),
    ]
