# Generated by Django 5.2.10 on 2026-01-17 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_forgotpasswordrequests_ip_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForgotPasswordRequests',
        ),
    ]
