// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7IngKFNkRjf6Isxw3TWApClyxhJjInnA',
    appId: '1:398415648692:android:4b2443f9f4a055fbf704e1',
    messagingSenderId: '398415648692',
    projectId: 'saaspos-9593d',
    storageBucket: 'saaspos-9593d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBalYV2Poo9asEWA2eXLBbst6E5A6HBzTA',
    appId: '1:398415648692:ios:77b27c52c84e0bb8f704e1',
    messagingSenderId: '398415648692',
    projectId: 'saaspos-9593d',
    storageBucket: 'saaspos-9593d.firebasestorage.app',
    iosBundleId: 'com.example.saasStock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHXcZKQA3U-5wkWDwE0Q4iz6ItjOoxmnU',
    appId: '1:398415648692:web:e2fe5097a29ae760f704e1',
    messagingSenderId: '398415648692',
    projectId: 'saaspos-9593d',
    authDomain: 'saaspos-9593d.firebaseapp.com',
    storageBucket: 'saaspos-9593d.firebasestorage.app',
    measurementId: 'G-XR3VV7KRML',
  );
}
