# Generated by Django 5.2.6 on 2025-12-20 11:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('barcode', models.IntegerField()),
                ('discription', models.TextField(blank=True, null=True)),
                ('buy_price', models.FloatField()),
                ('sell_price', models.FloatField()),
                ('quantity', models.FloatField(default=0)),
                ('min_quantity', models.FloatField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('monitor', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
