# Generated by Django 5.2.6 on 2025-12-28 23:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = [
  ]

  operations = [
      migrations.CreateModel(
          name='Category',
          fields=[
              ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
              ('name', models.TextField()),
              ('updated_at', models.DateTimeField(auto_now=True)),
              ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
          ],
      ),
      migrations.CreateModel(
          name='Products',
          fields=[
              ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
              ('name', models.TextField()),
              ('barcode', models.IntegerField()),
              ('discription', models.TextField(blank=True, null=True)),
              ('buy_price', models.FloatField()),
              ('sell_price', models.FloatField()),
              ('quantity', models.FloatField(default=0)),
              ('min_quantity', models.FloatField(default=0)),
              ('active', models.BooleanField(default=True)),
              ('monitor', models.BooleanField(default=False)),
              ('updated_at', models.DateTimeField(auto_now=True)),
              ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
              ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
          ],
      ),
  ]
