# Generated by Django 4.2.27 on 2026-01-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='large_count',
            field=models.FloatField(default=1),
        ),
    ]
