# Generated by Django 4.2.27 on 2026-01-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_large_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='large_count',
        ),
        migrations.AddField(
            model_name='products',
            name='unit_scale',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
